AWSTemplateFormatVersion: "2010-09-09"
Description: VPC FOR IBM
Resources:
  IBMVPC: #VPC 
    Type: "AWS::EC2::VPC"
    Properties: 
      CidrBlock: 10.0.0.0/20
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      Tags:
        - Key: Name
          Value: IBM-VPC

  IBMIGW: #IGW
    Type: "AWS::EC2::InternetGateway"
    Properties:
      Tags:
        - Key: Name
          Value: IBM-IGW


      